name: Tidy

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get changed files
        id: get-changed-files
        uses: lots0logs/gh-action-get-changed-files@2.0.6
        with:
          token: GITHUB_TOKEN
      - name: Check paths
        run: ls -la
      - name: Run Lint
        uses: ./Actions/Clang # Uses an action in the root directory
        id: clang-lint
        env:
          CLANG_ARGUMENTS: "-- -IHAP -IPAL -IExternal/HTTP -IExternal/JSON -IExternal/Base64"
          FILES_MODIFIED: ${{ steps.get-changed-files.outputs.modified }}
          FILES_ADDED: ${{ steps.get-changed-files.outputs.added }}
