name: CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: clang-tidy check
      uses: muxee/clang-tidy-action@0.0.1-rc1
      with:
        args: "-checks=* -IHAP -IPAL -IExternal/HTTP -IExternal/JSON -IExternal/Base64"
